services:
  - type: web
    name: meetnotes
    runtime: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MISTRAL_API_KEY
        sync: false
      - key: SARVAM_API_KEY
        sync: false
      - key: MISTRAL_MODEL
        value: open-mistral-7b
      - key: HF_HUB_DISABLE_SYMLINKS_WARNING
        value: "1"
